@startuml
skinparam activity {
  BackgroundColor #FFF9C4
  BorderColor Black
  FontColor Black
  ArrowColor Black
  DiamondBackgroundColor #E1F5FE
  DiamondBorderColor Black
  DiamondFontColor Black
}

title CU02: Registrar proyecto académico

|Estudiante|
start
:Identificarse como\nestudiante;

:Solicitar el registro\nde nuevo proyecto;

:Escribir el nombre\ndel proyecto;

:Escribir el enlace\ndel repositorio;

|Docente|
if (¿El enlace \n es válido?) then (Sí)
  :Guardar proyecto\nacadémico;
  
  :Confirmar registro\n del proyecto;
  stop
else (No)
  :Informar error con\n el enlace;
  stop
endif
@enduml